import = [
    "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
]

[font]
normal = { family = "iosevkaTerm Nerd Font Mono", style = "Regular" }
bold = { family = "iosevkaTerm Nerd Font Mono", style = "Bold" }
italic = { family = "iosevkaTerm Nerd Font Mono", style = "Italic" }
size = 16

